### ISSUE TITLE
Error starting project

### ISSUE THREAD

**Issue by ifyour** [stordahl/stordahldotdev#1]
Hi, I've also been learning honojs recently and when I start your project I get the following error, am I missing something?

```bash
pnpm run dev
```

```text
service core:user:worker: Uncaught Error: No such module "__STATIC_CONTENT_MANIFEST".
  imported from "index.js"
```

**Comment by stordahl** [comment]
@ifyour you need to configure your wrangler.toml to create a static asset bucket in Cloudflare - docs for that are [here](https://hono.dev/getting-started/cloudflare-workers#serve-static-files)

**Comment by ifyour** [comment]
@stordahl Thanks for the reply, it's booting up fine, I forgot I needed to configure this first! 🌚
